#define STACK_SZ 65536
#define CLONE_FLAGS CLONE_FS | CLONE_FILES | CLONE_SIGHAND | CLONE_VM | SIGCHLD
#ifdef DEV
    #define CLONE_FLAGS CLONE_VM|CLONE_FS|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID
#endif